version: "3.5"

services:
  django-backend:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: bash run_command.sh
    env_file: .env
    environment:
      - DEBUG=1
